### ISSUE TITLE
Not compatible with MVC5

### ISSUE THREAD

**Issue by digiface** [rebus-org/Rebus.Ninject#3]
Rebus.Ninject requires ninject (>= 4.0.0-beta-0134)
Ninject.MVC5 requires ninject (>= 3.2.0 && < 3.3.0)

**Comment by mookid8000** [comment]
I would rather say that Ninject.MVC5 is not compatible with Rebus.Ninject 😁 

How do you propose I solve this problem?

**Comment by digiface** [comment]
If using Rebus + Ninject + MVC5 is a common use case then adding compatibility note would be helpful, if not no worries

**Comment by mookid8000** [comment]
> If using Rebus + Ninject + MVC5 is a common use case then adding compatibility note would be helpful, if not no worries

I will do that 😄 

I'm not that familiar with Ninject, but it seems [.NET Core support was added in version 4](https://github.com/ninject/Ninject/blob/master/ReleaseNotes.md#version-40) – I guess this is the reason why Rebus depends on version 4 of it.

One could hope that Ninject.MVC5 would be updated soon to support version 4 of the container.

**Comment by mookid8000** [comment]
Thanks for pointing this out 😄
